### ISSUE TITLE
Improper repo and release structuring

### ISSUE THREAD

**Issue by daluu** [PcapPlusPlus/pcapplusplus.github.io#74]
I see it looks like the repo/project codebase is under

https://github.com/PcapPlusPlus/pcapplusplus.github.io

Normally `pcapplusplus.github.io` would be for developer's own website hosting relating to their github hosted code, can be a website, blog, etc.

The code itself would be hosted like

https://github.com/username/PcapPlusPlus

where in this case, username can be same as in repo for a result of

https://github.com/PcapPlusPlus/PcapPlusPlus

but that's not what we see.

And I see in github profile, releases (of website) have been established as separate repos, I don't think that's how it should be done either. You tag releases and they show up under say https://github.com/PcapPlusPlus/pcapplusplus.github.io/releases for your current repo structure. But I suppose you want to make it viewable that's why, but why would anyone want to view different versions of the website? If it's just about code, we can just download the different release versions.

But I suppose things are too late now that you have stuff hosted and published. But just an FYI.

**Comment by seladb** [comment]
@daluu this repo contains the documentation for the PcapPlusPlus project: https://github.com/seladb/PcapPlusPlus

You may ask why PcapPlusPlus codebase isn't under the @PcapPlusPlus user? This is because I started the project many years ago, and at that time I didn't realize I would need a documentation web-site so I started it under my username (@seladb). I could move it to the @PcapPlusPlus but many people already know and use it under https://github.com/seladb/PcapPlusPlus and I don't think it is worth the confusion it will create.

Regarding versioninig: the documentation web-site went through several major cycles. In the beginning it was a very simple HTML page, then more sophisticated HTML pages, then it moved to be based on [Jekyll](https://jekyllrb.com/), and only then it moved to its current version based on [Docusaurus](https://docusaurus.io/). One of the main reasons I decided to switch to [Docusaurus](https://docusaurus.io/) is its version support - which didn't exist in [Jekyll](https://jekyllrb.com/) and of course not in plain HTML.

That's why all web-site versions prior to PcapPlusPlus 21.11 are stored in their own repos. These are the web-site versions that were built on top of  [Jekyll](https://jekyllrb.com/) or HTML. Since 21.11 all versions are stored in this repo as you can see here: https://github.com/PcapPlusPlus/pcapplusplus.github.io/tree/master/versioned_docs

Please let me know if you have any questions

**Comment by seladb** [comment]
@daluu should we close this issue?

**Comment by daluu** [comment]
Yes, thanks for the clarification of info.
